1.0.2 Minor regbits.hxx, major unittest update

diff --git a/unittest/bad/linux/Makefile b/unittest/bad/linux/Makefile
--- a/unittest/bad/linux/Makefile
+++ b/unittest/bad/linux/Makefile
@@ -1,5 +1,5 @@
 # regbits: C++ templates for type-safe bit manipulation
-# Copyright (C) 2019 Mark R. Rubin
+# Copyright (C) 2019,2020 Mark R. Rubin
 #
 # This file is part of regbits.
 #
@@ -18,8 +18,6 @@
 # <https://www.gnu.org/licenses/gpl.html>
 
 
-GOOD	     ?= -UGOOD
-
 CXX_STANDARD ?= c++11
 OPTIMIZE     ?= -O1
 DEBUG        ?=
@@ -30,7 +28,6 @@ SRCS = $(subst ../,,$(wildcard ../*.cxx))
 OBJS = $(SRCS:.cxx=.o)
 
 unittest: $(OBJS)
-	@ rm -f *.o
 
 .PHONY: clean
 clean:
@@ -45,16 +42,16 @@ CXXOPTS =  -Wall		\
 	  $(DEBUG)		\
 	  $(INCLUDES)		\
 	  $(EXTRA_CXX)		\
-	  $(GOOD)		\
 	  -DREGBITS_PERIPH_BASE=$(PERIPH_BASE)
 
+
 %.o: %.cxx
-	@- if $(CXX) -c $(CXXOPTS) $< -o $@			\
-	> /dev/null 2>&1 ;					\
-	then							\
-	    if [ $(GOOD) == -UGOOD ] ; then			\
-		    echo "$< compiled but should have failed" ;	\
-	    fi							\
-	elif [ $(GOOD) == -DGOOD ] ; then			\
-	    echo "$< failed but should have compiled" ;		\
-	fi
+	@ if $(CXX) -c $(CXXOPTS) -UGOOD $< -o $@ > /dev/null 2>&1 ;	\
+	then								\
+		echo "$< -UGOOD compiled but should have failed" ;	\
+	fi ;								\
+	rm -f $@ ;							\
+	if ! $(CXX) -c $(CXXOPTS) -DGOOD $< -o $@ > /dev/null 2>&1 ;	\
+	then								\
+		echo "$< -DGOOD failed but should have compiled" ;	\
+	fi								\
